### ISSUE TITLE
Problem wit new files or opened files; addon not acitvated; solution needet; quickly;

### ISSUE THREAD

**Issue by marko090591** [mariusv-github/ElasticTabstops#1]
Hello

When opening or creating new files addon is not acitvated. Where can i find a option to activate addon in all new and oppened files. Activating it in all is very time consuming.

A user Marko Skvarča about the the same problem bellow.

https://community.notepad-plus-plus.org/topic/23843/new-version-1-5-for-elastic-tabstops/9

Picture
![nov_1_-_Notepad++ 12 12 2022 12 21](https://user-images.githubusercontent.com/52610785/207033057-a475f804-ccbf-4665-8f14-f94c09c4650b.png)

Settings used are listed bellow.

[Default settings]
sel_only=0
glob_tabs=1
min_padding=1
keep_leading_tabs=1
remember_enabled_files=1
extensions=!*

**Comment by marko090591** [comment]
Settings are listed bellow.

[Default settings]
sel_only=0
glob_tabs=1
min_padding=1
keep_leading_tabs=1
remember_enabled_files=1
extensions=!*
[C:\Users\MarkoSkvarca\OneDrive - unichem.si\Dokumenti\nov 1.txt]
sel_only=0
glob_tabs=1

**Comment by mariusv-github** [comment]
Hi Marko,

First, is better if you read the ET help file before ask "quickly a solution". I written the help file for someone like you who want to change the default settings!

Secondly, the answer you need is on line 73 of ET help: if you want to active all files by default all you have to do is changing the extensions option, save options (and then eventually restart your NPP):

extensions=*

But, thirdly: be aware when activating ET by default: line 44 of ET help.

**Comment by marko090591** [comment]
Ok. Thank you.
